import type { Metadata } from "next";
import "./globals.css";
import styles from "./header.module.scss";
import Link from "next/link";


export const metadata: Metadata = {
  title: "MichaelHefner.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <h1 className={styles.logo}>michaelhefner.com</h1>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/code">Code</Link>
          </nav>
          </header>
        {children}
      </body>
    </html>
  );
}
